### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by quietlyconfident** [adieu/vobject#3]
Would you be open to incrementing the version number to 0.8.1d or even 0.8.2 ?  Right now, this repository has the same version number as the dead project on skyhouseconsulting.com .  This causes some trouble because pip / easy_install can't differentiate between a build of this one (which has fixes from as recently as 5 months ago) and the old one (which was released ~ 5 years ago).

**Comment by adieu** [comment]
I'm totally fine with bumping the version number. But I have to say I cloned the official repo just to make some quick fixes for one project I was working on and didn't put much efforts afterwards. Since we don't have permission to edit the vobject project in pypi at https://pypi.python.org/pypi/vobject/, people could only install this version by pip install git+git://github.com/adieu/vobject.git. I'm not sure how much the difference bumping the version number will make. If  there's some real benefits there, I'm happy to make the change.

BTW, you could always clone this repo and edit it yourself if you want.

**Comment by quietlyconfident** [comment]
I considered cloning it myself, but you have made some fixes and at least some other people are following / watching this repository, so I think it is the next-best thing at the moment to an actively maintained object :)

The problem we encounter is, if you are going to make a local pypi (e.g. using pip’s download cache feaure), the other vobject, without the fixes we rely upon which are present in this version, eventually sneaks in and pollutes the cache.  It creates some uncertainty about what you’re ultimately going to be installing.

So yeah, if you wouldn’t mind bumping the version , it would help me.
